# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    influxdb_client:
      class: InfluxDB\Client
      arguments: ['%influxdb_host%', '%influxdb_port%']
    influxdb_database:
      class: InfluxDB\Database
      arguments: ['%influxdb_db%', '@influxdb_client']
